### ISSUE TITLE
build issues 

### ISSUE THREAD

**Issue by pbermell** [zivid/cpp-extra-samples#1]
Hello, 
I am trying to build the samples but I get an error. Any hints? Thanks. this is what I get on the console when following instructions on github page: 

xtcdev@xtcdev01:~/repos/cpp-extra-samples/Zivid/build$ cmake ..
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:28 (file):
  file COPY cannot find "/bin_debug/plugins".

CMake Error at CMakeLists.txt:29 (file):
  file COPY cannot find "/bin/plugins".

-- Configuring incomplete, errors occurred!
See also "/home/xtcdev/repos/cpp-extra-samples/Zivid/build/CMakeFiles/CMakeOutput.log".

**Comment by SatjaSivcev** [comment]
Can you confirm that you have rebooted your pc after installing Zivid Software? A problem with ENV variables is that they are not set before you start a new login session. That may be the source of error here.
It seems that $ENV{ZIVID_INSTALL_FOLDER}/bin/plugins/ expands to /bin/plugins/ meaning $ENV{ZIVID_INSTALL_FOLDER} is empty, can you please check the value of this system variable and also the existance of C:\Program Files\Zivid\bin\plugins or similar location where you have installed Zivid?

**Comment by nedrebo** [comment]
It seem you are trying to compile this on Linux, unfortunately the CMake files have not been tested there and they contain Windows paths. This should be easy to fix and you can expect an update soon.

For now you can comment out the following lines, they are not needed on Linux anyway. The code should then build and run on Linux.

https://github.com/zivid/cpp-extra-samples/blob/2abbfdec0fc726841c10bb0cf8a96d687508ec2f/Zivid/CMakeLists.txt#L28-L29

The comment above was assuming that you used Windows you can disregard it.

**Comment by pbermell** [comment]
Thanks, 
Yes, I am trying this in Linux. Will give it a go commenting the lines and wait patiently for the updates!

**Comment by knatten** [comment]
@pbermell this issue is now fixed. Can you please try again?

Be aware however that the Linux experience is still not very smooth. In particular, the examples which use visualization need Qt 5.11 specifically. We're hoping to fix this in not too long. Feel free to ping me in this thread if you run into further issues.

**Comment by knatten** [comment]
Closing due to no response.
