### ISSUE TITLE
Set up CI that builds all examples on Linux

### ISSUE THREAD

**Issue by knatten** [zivid/cpp-extra-samples#15]
Refer to https://github.com/zivid/zivid-python and do it the same way

**Comment by nedrebo** [comment]
Zivid officially support Ubuntu 16.04 and 18.04, both those should be covered.

However, the additional distributions tested against in zivid-python is probably overkill and for this and will only result in maintenance overhead.

**Comment by knatten** [comment]
It's probably a good idea to also check that samples with missing dependencies build when the dependency is turned off. For instance setting `OpenCV_DIR` to a non existing directory and `USE_OPENCV=OFF` should work.
This will reveal if we add a sample to `CMakeLists.txt` without adding it to the proper dependency lists.

(Idea came from https://github.com/zivid/cpp-extra-samples/pull/23#discussion_r325063844)

**Comment by knatten** [comment]
Should build on both Ubuntu 18.04 and 16.04.

**Comment by knatten** [comment]
We're building on Linux in CI. I've added #42 and #43 to improve further.
