### ISSUE TITLE
Set up CI for Linux and Windows

### ISSUE THREAD

**Issue by nedrebo** [zivid/cpp-extra-samples#3]
Set up a CI for building on the supported platforms (W10, U16, U18).

We use Azure Pipelines for CI.

Refer to https://github.com/zivid/zivid-python for how to do it, especially look into https://github.com/zivid/zivid-python/blob/master/azure-pipelines.yml. Building this repository should be very similar, just simpler since all the Python things can be skipped.

Ask @nedrebo for help enabling this in Azure and @apartridge or @trym-b for code changes.

**Comment by nedrebo** [comment]
This is only partially fixed by #13. Still missing building with warnings, clang-tidy and coverage on Windows and Ubuntu 16.04 as well.

**Comment by nedrebo** [comment]
@knatten Please re-open, seems I cannot do it (https://stackoverflow.com/a/21333938).

**Comment by nedrebo** [comment]
This issue seems to have been split into #15, #16 and #17. No need for re-opening.

**Comment by knatten** [comment]
Yeah I split it into more focused issues. Should have made a note about it here.
