### ISSUE TITLE
Set up CI for Ubuntu 16.04

### ISSUE THREAD

**Issue by knatten** [zivid/cpp-extra-samples#42]
We're currently only building on 18.04, need 16.04 as well.

**Comment by nedrebo** [comment]
Use the build matrix feature, like we are doing in zivid-python (soon) so that all of or public repositories do build matrices the same way. Easier to reason about, maintain and move between projects.

**Comment by knatten** [comment]
That's indeed the plan :)

**Comment by knatten** [comment]
Fixed by #50
