### ISSUE TITLE
Don't depend on unreleased Eigen

### ISSUE THREAD

**Issue by knatten** [zivid/cpp-extra-samples#44]
Currently we depend on features in Eigen which are not released yet. We should only depend on released versions of our dependencies. This is a blocker for using Eigen in CI.

Take a look at the sample that needs unreleased Eigen, see if we can make it work with an official version.

**Comment by SatjaSivcev** [comment]
The problem is that 3.3.7 does not support '.reshaped'
https://eigen.tuxfamily.org/dox-devel/group__TutorialReshape.html

A potential solution is to use .Map'
https://stackoverflow.com/questions/56370502/eigen-3-4-reshaped

**Comment by knatten** [comment]
Fixed in #45
