### ISSUE TITLE
Move all samples inside a directory

### ISSUE THREAD

**Issue by knatten** [zivid/cpp-extra-samples#48]
Currently all the samples are in several directories in the root of the repo. This makes it hard to do a proper out-of-source build. I suggest moving all the code inside a directory `src` or something.

This will also make it simpler for CI scripts to for instance not accidentally lint generated files in the build directory etc.

Remember to update the readme after this. Might also need to update KB.

**Comment by SatjaSivcev** [comment]
Is there a reason not to put them in the rood of the repo? If they all are going to be in the same directory why make a new one and not use the root?

**Comment by SatjaSivcev** [comment]
Or is ok to have the samples in different directories but all the directories in one 'src' directory?

**Comment by knatten** [comment]
Yeah the plan is to just move the entire structure as it is into one `src` directory.

It's recommended practice for cmake to have the source and build directories entirely separate. It also makes it simpler for custom CI scripts. We for instance currently require all our source files to be formatted correctly, but that script also finds generated files in the build directory and complains about them.

Currently the only way to have separate directories is to make the build directory outside of the repo root. It would be simpler if we could allow having it inside the repo root. It would also make the repo a bit tidier imo.

If we had something like this, it would be a lot simpler to separate what's source files and what's build files:
```
src/
  CMakeLists.txt
  Downsample/
  Zivid/
  ZividOpenCV/
  (...)
build/
README.md
LICENSE
(...)
```
etc.

What do you think?

**Comment by SatjaSivcev** [comment]
That sounds good to me.

**Comment by SatjaSivcev** [comment]
Is ${CMAKE_CURRENT_SOURCE_DIR} in CMakeLists supposed include /src/ or should that be hardcoded?

**Comment by knatten** [comment]
If you move all of the source inside `src`, and also move `CMakeLists.txt` and the `cmake` directory in there, you shouldn't have to make any other changes to any of the CMake stuff. Everything should just work.

(You need to update `build.sh` for CI to work though, since you're moving stuff around. I think all you need is to add `/src` to the end of the path [here](https://github.com/zivid/cpp-extra-samples/blob/master/continuous-integration/linux/build.sh#L39))

**Comment by SatjaSivcev** [comment]
Ok. So it is ok not to have `CMakeLists.txt` in the root?

**Comment by knatten** [comment]
That's at least my opinion, and how we do it in the main Zivid repo. But I'm not an expert here.
