### ISSUE TITLE
Update copyright year 

### ISSUE THREAD

**Issue by torbsorb** [zivid/cpp-extra-samples#63]
All license files should have their copyright year updated. This applies to all repos, not only this.

**Comment by SatjaSivcev** [comment]
I think this is fixed @torbsorb with https://github.com/zivid/cpp-extra-samples/commit/15d695da20c9cf9d97eb2a7f6b2b6bd4999a0558

**Comment by torbsorb** [comment]
It has been updated in the -samples repos.
