### ISSUE TITLE
Incorrect filename used for saving

### ISSUE THREAD

**Issue by torbsorb** [zivid/cpp-extra-samples#67]
https://github.com/zivid/cpp-extra-samples/blob/54bf513806f72f2e782cc620ccd4e85db96d50b3/source/Applications/Basic/Visualization/CaptureHDRLoop/CaptureHDRLoop.cpp#L52-L54

Iris values are 10, 20 and 30. File names should reflect that.

**Comment by SatjaSivcev** [comment]
It seems this is fixed @torbsorb, see https://github.com/zivid/cpp-extra-samples/blob/master/source/Camera/Basic/CaptureHDR/CaptureHDR.cpp

**Comment by torbsorb** [comment]
Yes
