### ISSUE TITLE
Make overview of dependency versions

### ISSUE THREAD

**Issue by knatten** [zivid/cpp-extra-samples#73]
Fill in this table to figure out which packages are available in which versions of Ubuntu. If we're able to downgrade some of our dependencies to support those versions, we can more easily run more samples to CI:

| Dependency | U 16.04| U 18.04 | U 20.04 | Current req. | Could downgrade to|
|---|---|---|---|---|---|
|  Eigen  |  |  |  | 3.3.7 |  |
|  PCL  |  |  |  | 1.2 |  |
|  OpenCV  |  |  |  | 4.0.1 (or 4.1.1?) |  |

**Comment by SatjaSivcev** [comment]
I think this is irrelevant now since we build all samples in CI (20.04). Can we close the issue?

**Comment by knatten** [comment]
Indeed. Nice job getting CI for everything! <3
