### ISSUE TITLE
Use relative links to samples in README

### ISSUE THREAD

**Issue by knatten** [zivid/cpp-extra-samples#8]
The links are currently absolute, because that's the only way to make them work in the Knowledge Base.

We need to figure out why, and hopefully fix so we can use relative links here and still make it work there.

**Comment by knatten** [comment]
When fixing this, also fix the other repositories.

**Comment by torbsorb** [comment]
I didn't realize you posted this issue. I don't see relative links as an issue in KB anymore, so I've started adding it to the other repos. I'll add it here too.

**Comment by SatjaSivcev** [comment]
Closed in https://github.com/zivid/cpp-extra-samples/pull/78/commits/53f7a88d32cb4500a12ae69698788958e56cf18d
