### ISSUE TITLE
Add CI for Ubuntu 20.04

### ISSUE THREAD

**Issue by knatten** [zivid/cpp-extra-samples#96]
~Have to wait until Zivid officially supports Ubuntu 20.04.~ Edit: This might already work even if it's not officially supported yet.

**Comment by nedrebo** [comment]
Not really, we unofficially support all distros, installing the older packages should work just fine. In zivid-python we even have Arch Linux and Fedora in the CI.

**Comment by torbsorb** [comment]
I'm working on this for #91
